language: go
go:
  - 1.13
env:
  global:
    secure: "vJWDbLFbpcY+GWuRmPKy1NIs2vRIItyUYidqwpxmMKMUVwqFcW7PwHCB7YncPvS5nqiyczkJ2017C9UtVzpC4kcbR72zEytTK3rwVu4BRyNzZjGUCahvESKYxzgE9K8XMOgMtkTGRRVncckclM/Qk3/XsyOjt80BPr4ZIIsstdGXgAFC279to+vIyokyXaP3vZG5Wm1wWx6X6raOWl9CR2gxM6R+WVXB5wLS1yhhgeZwdX9wbiyM9qLj0JuIFqWbdwW4vfQEa1eqyncvsEt/4RotKmAqpeMoc73q4KkA8TzVO3uiuZhO7nH5oJj9R4YXK3Vzf6lX/mwV7XY2qZcrvtodsM34Y7iejrWtC9vuETh13DWDpyXauEVtoFNMv8LGEVPIgU7+96919Tic33djHTbSeWsWzj7QBwn0AacFGWjDA3p/V+/cIpTJyV0Ie9xLp8D4hiAl7jKiDtAQjp/ffCiLPW/uiv1IKRsAWS8QHbFy0izSzTpKBuY4lzQQZXEkNN3GoxEpH464GpNsk01VFjjKGEQ7PI+l1Q8000lflnhAMHbsqM/mMqKBgp7Zh/b7pL5dPaKZyEXTxnSovolD/ehqlkal8VGJjAeDDmEHpzAeUbzmk5XJDHE2cRy5O4xguKxBsOFUeERhWyvLeuvli4nIit5WKOtxfHqhCAHyKxc="
jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: build
      script:
        - make build
      deploy:
        provider: releases
        skip_cleanup: true
        name: "pax $TRAVIS_TAG"
        edge: true
        file:
          - bin/darwin/pax-darwin-amd64
          - bin/linux/pax-linux-amd64
          - bin/windows/pax-windows-amd64.exe
        on:
          repo: liamg/pax
          tags: true

