language: go
go:
  - 1.13
jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: build
      script:
        - make build
      deploy:
        provider: releases
        skip_cleanup: true
        name: "pax $TRAVIS_TAG"
        file:
          - bin/darwin/pax-darwin-amd64
          - bin/linux/pax-linux-amd64
          - bin/windows/pax-windows-amd64.exe
        api_key:
          secure: "Cwsft0N+qiZjJl1droUbr6J/ktIy94hkhzNfeqvkarIXOU3EsetDl0W2T9j+tMRj7CRoQ0L+LJBFsiUEJ/zNwo86wplIsKdO618IfW4mU/uyxBNDEZxmX33lVE/XXhAfzUEmSj1XjlZDZIEo1YQZC+jaM7mGhPHnBqQJxL01m64P0GN47EvAws9I1TNo7GWjwqSBFS3plCYvaRUNurWJchEoNFAFr+0dfcdRskFljTdE8GUM41BVNrJhIwp2XyFRn/STmOx+qeukmBURpLWTZ1c3+0jTiH5lMp9HVIb2BZvvHBEZ517+YTXV8Deuvzq3xqsER+onzSxAhowF+ZKbpQoVDRpgYqiwaCX/dNF0YNb20Lhi2YB8b9Y/DBKNNSNeSrq/7oJG+w2v6sAZOT5LNKZdDNYKiAxtRPU01XFpQ/SOxY2BYW1yTsN398NJ/UUZh4wLFs/x7BkfiubZlv0+N/EwnfT8BHiWzetCiHOgCx5Qk02CyJ1DYiMlGrwKu5ehUWbgu2eVpxGK8xzp9MMOkxERfghxP2/afeUyasgEClLqJyHRBShYWwtbaFoDklYsx78ebQ3o4HP1vdA8EORgIGHOi2dILplL3DXT2AXHgRe43h9zMsA2/jGxyKrMe2LjY+j5uBRk7h60BgImhKgvZMi5A9Pg3Hda9VcpUybvGtc="
        on:
          repo: liamg/pax
          tags: true