language: go
go:
  - 1.13
env:
  global:
  - secure: "0b4ONlNY58YkyQ8ykvmm+MNvOh58Iq/mkJJPyf2dI2fnzNWjtHwjIcQ+BmOjbUYm4MOmp1p8LvXEwkm8s/2gjuwHUQyoPVmGc7YnsG6a57JPou+BFCtXV0yP1Enumz2Ms5/fVlFsBv1aXdqgbqghIRKUUg33Skx9zgZSd0oWhIKBbg7HU8/asrB7zteBnMeqTPffSj4+cIJ2i0dDD2aXTbB2KN+oBSngg2POxXxQQNy+FQZXqSRe/OLc4etT8/TBZL7z4PnYdhedXzUzrLb0W6GkVCUsblD3yB/l+adfbvglezbRQst3J9u0AdUsbJMzsTNowO+5qjmUApoJ4WPZifjsSwdU1r8tSMVhS4kIiUIIwV7ExDeYDj9FwNivEArAMtvhh3YqV+oCblXXl/NROxv+LwkwN1qDqjoRsd4n/43WVkhWMOcQSjiVQ00P+HdPpOSKS+AYhKESnnVnuMkpSOeeWLQIwyy2VzYRLUstc2mX0JG/3FUEhrNF9uTESEJwIikwctfWvm5Ra9Wr0nDKg7rzn4cuFpRLawvOD9kHgVEpSimWa/0LgOXrB7R8MVp3uxaulOba7wqo8QSP5xSMeBzKlM0Mc5JxLq4b6zuVjBtd+jLPnFZHt98hMPDGPmZMyACXfUPdG+RN6c7K1qkz6OB3vTSBkft5P2np12IEr1A="
jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: build
      script:
        - make build
      deploy:
        provider: releases
        skip_cleanup: true
        name: "pax $TRAVIS_TAG"
        edge: true
        file:
          - bin/darwin/pax-darwin-amd64
          - bin/linux/pax-linux-amd64
          - bin/windows/pax-windows-amd64.exe
        on:
          repo: liamg/pax
          tags: true

