language: go
go:
  - 1.13
jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: build
      script:
        - make build
      deploy:
        provider: releases
        skip_cleanup: true
        name: "pax $TRAVIS_TAG"
        file:
          - bin/darwin/pax-darwin-amd64
          - bin/linux/pax-linux-amd64
          - bin/windows/pax-windows-amd64.exe
        api_key:
          secure: "GvKzFEz6UyQzjHwtnRbzURsckrxXnkIK1uT+pZxcIBs7nQy6WNIVM2Om86LQ8G5FbETuM7GOi0NYwpMLZEq5iM9fhZzqeMrbewj4YtvjxPRGu7XXbMyJX6Wk/bwMRfPqclQM/dan1wKwu01VObiTU282xy9Eb5wsVEmMRrWBUO/ur+NkEM9DQqAgMcW3f8KrclS0Ikx21b1fxFMZnyli+Aeq01e94qXB6G7DbRQhrbb8KrYcry8SA0n0IceFCcBNfcdrHjWmfFHI54MmDBjBpMAvIzS6Tx6ypr6MtjspcrMqCFUTL52nE53jmase+amOmYcTxPA6cqSgq43NCy9E0NSRovExrx6m6XOCNnZYXkiyCsFrgc+x51pe1beiJQ9djRX/j32ACrbaBbnMz5W21YHVGAOIrmm6w+O9DOAecDOEU68lgXTvQzLX8JgeRgwKVwpY1U1Ua4WEm7neLTgbjWdFOQ5Gh9JRpW0FSuXKA/slNAjy0oflYyJ1vdKVPrMZR1qF2RijaxRyatKfEljwobDyx0fSduZQSJCDUln2fm1Qb0HOgKmKCVim3RjgA2qmQrYAdHtjBpIWlvV0NckBakqOiChF70rFqge3aXImoWFVl9lWZsDsKxDd0RpvltXLo1Q4KXfY+j1j6SKHa18HTmPNDg6TWUZcpcYP0YOiNTw="
        on:
          repo: liamg/pax
          tags: true

